[package]
name = "furry"
version = "0.1.0"
edition = "2021"

[dependencies]
pyrite = { path = "../pyrite/pyrite" }
inline-spirv = "0.1.6"
bytemuck = "1.14.0"
ash = "0.37.3+1.3.251"
anyhow = "1.0.71"
nalgebra = "0.32.3"
gltf = "1.3.0"
uuid = "1.5.0"
